### PR TITLE
roles/wazo_kamailio/tasks/main.yml: remove kamailio repo

### PR DESCRIPTION
**Pull request by fredericlepied**
use packages from wazo's repo

### CODE REVIEW

**Comment by tranchitella** [comment]
@fredericlepied merged master and rechecking, I think it can actually pass the tests...

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
> @fredericlepied merged master and rechecking, I think it can actually pass the tests...

@tranchitella It seems the new kamailio packages don't work. @sduthil proposed to take a look. Perhaps you could do it together?

**Comment by tranchitella** [comment]
@sduthil @fredericlepied sure, we have a Vagrantfile in the repo and we can easily check it locally. I still don't get why we are repackaging Kamailio instead of using (or just importing) the Debian packages from the official repo, though.

**Review by sduthil — APPROVED** [review]

**Pull request merged**
