### PR TITLE
wazo-auth is now installed without SSL/TLS

### PR DESCRIPTION
**Pull request by fblackburn1**
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689

### CODE REVIEW

**Review by pc-m — DISMISSED** [review]

**Comment by sboily** [comment]
What's the status with this PR?

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
> What's the status with this PR?

Missing one ... caused by an annoying bug with JIRA-github that doesn't update ticket PR on JIRA when merged on github ...
Screenshot from 2020-04-29 07-22-20

**Comment by sboily** [comment]
> > What's the status with this PR?
> 
> Missing one ... caused by an annoying bug with JIRA-github that doesn't update ticket PR on JIRA when merged on github ...
> Screenshot from 2020-04-29 07-22-20

Yes i know you love Jira :)

**Review by pc-m — APPROVED** [review]

**Pull request merged**
