### PR TITLE
debian buster testing

### PR DESCRIPTION
**Pull request by sileht**
Depends-On: https://github.com/wazo-pbx/sf-jobs/pull/14

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
\o/

**Review by sduthil — APPROVED** [review]

**Review by sduthil — APPROVED** [review]

**Comment by fredericlepied** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Comment by sileht** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Comment by sileht** [comment]
regate

**Pull request merged**
