### PR TITLE
improve comment in inventory file

### PR DESCRIPTION
**Pull request by fblackburn1**
reason: For someone that don't know ansible, it maybe not obviously

### CODE REVIEW

**Comment by fblackburn1** [comment]
I'm not sure of the solution:
In the [documentation](https://wazo-platform.org/install/unified-communication) we say to modify the inventory file according `your preferences`. But sometime, the reader don't know what is ansible and the first line in the file say to change the host ... which is unnecessary when you follow the doc
So maybe we should just write
```diff
 # -*- conf -*-
-# You only have to change [uc-engine-host] and set variables according
-# to your needs (e.g. remove localhost line and add the IP on which
-# wazo-platform will be installed)
+# You only have to set variables according to your needs
 
 [uc-engine-host]
 localhost ansible_connection=local
```

**Review by pc-m — APPROVED** [review]

**Comment by fblackburn1** [comment]
@pc-m there are two solutions, which one you approve?

**Comment by pc-m** [comment]
> @pc-m there are two solutions, which want you approve?

I love having a example in the description but since the installation instruction are meant to be executed from localhost maybe there's no need to change anything.

**Comment by fredericlepied** [comment]
regate

**Comment by fredericlepied** [comment]
regate

**Pull request merged**
