### PR TITLE
Use pelican-buster by default instead of wazo-dev-buster

### PR DESCRIPTION
**Pull request by bloom1**

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
I think wazo-ansible-router is still broken. Am I right @fredericlepied ? Is it necessary?

**Comment by fredericlepied** [comment]
yes it seems to still be broken. @tranchitella or @alexsosic could you fix that ? It's blocking any change to be merged in wazo-ansible...

**Comment by fredericlepied** [comment]
@bloom1 we also need to change the zuul job to use the dev version instead of the stable one.

**Review by fredericlepied — CHANGES_REQUESTED** [review]
we need to change the zuul job to use the devel version instead of the stable one.

**Comment by fblackburn1** [comment]
Since this PR need to be merged ASAP, when `wazo-ansible-uc` and `wazo-ansible-docker` will pass I'll merge it

**Pull request merged**
