### PR TITLE
WAZO-1552: rename xivo-sysconfd to wazo-sysconfd

### PR DESCRIPTION
**Pull request by bloom1**
Depends-On: https://github.com/wazo-platform/xivo-sysconfd/pull/24

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by fblackburn1** [comment]
Depends-on: https://github.com/wazo-platform/wazo-sysconfd/pull/26

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
